// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiCevs4lkE56lG4sfEIvnoRZFXI0fC6GQ',
    appId: '1:722990973080:ios:c87c2f1ecdb5444224d0ed',
    messagingSenderId: '722990973080',
    projectId: 'delimart-ra184',
    storageBucket: 'delimart-ra184.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjects',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrssWjn0MQIQ2iH_M1BmjvG0AD02l4e7I',
    appId: '1:722990973080:web:655b48e786cf70fb24d0ed',
    messagingSenderId: '722990973080',
    projectId: 'delimart-ra184',
    authDomain: 'delimart-ra184.firebaseapp.com',
    storageBucket: 'delimart-ra184.firebasestorage.app',
    measurementId: 'G-LMYV3SMV77',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiCevs4lkE56lG4sfEIvnoRZFXI0fC6GQ',
    appId: '1:722990973080:ios:c87c2f1ecdb5444224d0ed',
    messagingSenderId: '722990973080',
    projectId: 'delimart-ra184',
    storageBucket: 'delimart-ra184.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjects',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNFmnXVlTS0T7bc4N0IippvuuoG3cj1tM',
    appId: '1:722990973080:android:9636f565e2df6ed724d0ed',
    messagingSenderId: '722990973080',
    projectId: 'delimart-ra184',
    storageBucket: 'delimart-ra184.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrssWjn0MQIQ2iH_M1BmjvG0AD02l4e7I',
    appId: '1:722990973080:web:98022341c5e5d0c524d0ed',
    messagingSenderId: '722990973080',
    projectId: 'delimart-ra184',
    authDomain: 'delimart-ra184.firebaseapp.com',
    storageBucket: 'delimart-ra184.firebasestorage.app',
    measurementId: 'G-D63Y5H81PM',
  );

}